//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sex
    {
        public Sex()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int SexId { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
