//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Solutions = new HashSet<Solution>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.Categories = new HashSet<Category>();
            this.UserProfiles1 = new HashSet<UserProfile>();
        }
    
        public int TaskId { get; set; }
        public string Title { get; set; }
        public string TaskText { get; set; }
        public Nullable<int> Author { get; set; }
        public System.DateTime Added { get; set; }
        public Nullable<System.DateTime> FirstSolve { get; set; }
        public int SolutionsCount { get; set; }
        public int Attempts { get; set; }
    
        public virtual ICollection<Solution> Solutions { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<UserProfile> UserProfiles1 { get; set; }
    }
}
