//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.Solutions = new HashSet<Solutions>();
            this.UserProfile1 = new HashSet<UserProfile>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int TaskId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public int Author { get; set; }
        public Nullable<System.DateTime> Added { get; set; }
        public Nullable<System.DateTime> FirstSolve { get; set; }
        public Nullable<int> SolutionsCount { get; set; }
        public Nullable<int> Attempts { get; set; }
    
        public virtual ICollection<Solutions> Solutions { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserProfile> UserProfile1 { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
