//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.Tasks2 = new HashSet<Task>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public int Rating { get; set; }
        public int TasksCount { get; set; }
        public int SolutionsCount { get; set; }
    
        public virtual Sex Sex { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual ICollection<Task> Tasks2 { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
